---
title: "Class11"
author: "Xuerui HUang"
date: "5/8/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#load data
db <- read.csv("Data Export Summary.csv")
#read(db)

#total number of protein structure
sum(db$Total)

#percent of protein
db$Perc <- (db$Total/sum(db$Total))*100
```

## Section 3
```{r}
library(bio3d)
pdb <- read.pdb("1hsg.pdb")
```

```{r}
aa321(pdb$seqres)

pdb$atom
```
```{r}
ca.inds <- atom.select(pdb, "calpha")
ca.inds

# Select chain A
a.inds <- atom.select(pdb, chain="A")
# Select C-alphas of chain A
ca.inds <- atom.select(pdb, "calpha", chain="A")
# We can combine multiple selection criteria to return their intersection
cab.inds <- atom.select(pdb, elety=c("CA","CB"), chain="A",
resno=10:20)
```
```{r}
prot <- atom.select(pdb,"protein",value = TRUE)
write.pdb(prot,file = "1hsg_protein.pdb")

prot <- atom.select(pdb,"ligand",value = TRUE)
write.pdb(prot,file = "1hsg_lig.pdb")

library(bio3d.view)
library(rgl)
view(pdb, "overview", col="sse")
```





