---
title: "lecture7_proj: R: Functions and packages"
author: "Xuerui HUang"
date: "4/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
source("http://tinyurl.com/rescale-R")
```
```{r}
#test the rescale function
rescale(1:10)

#test function
x <- c(1:10,"string")
is.numeric(x)

```

## Function for recognize NA in two vectors
```{r}
#sample input
x <- c( 1, 2, NA, 3, NA)
y<-c(NA,3,NA,3, 4)

sum(is.na (x)&is.na(y))

#function for checking whether two elements on the same position of two vectors have NA
both_na <- function(x,y){
  sum(is.na(x)&is.na(y))
}

```
## function for grading homework
```{r}

student1 <- c(rep(100,time= 8),90)
student2 <- c(100,NA,rep(90,time = 4),97,80)

#forloop
overall_grade <- function(stud_vec){
  stud_vec <- stud_vec[!is.na(stud_vec)]
  min_val <- min(stud_vec)
  for (i in 1:length(stud_vec)){
    if (stud_vec[i] == min_val){
      stud_vec <- stud_vec[-i]
      break
    }
  }
  mean_score <- mean(stud_vec)
  return (mean_score)
}

#better way
overall_grade_2 <- function(stud_vec){
  if (sum(is.na(stud_vec) >0)){
    stud_vec <- stud_vec[!is.na(stud_vec)]
  }
  
  (sum(stud_vec)-min(stud_vec))/(length(stud_vec)-1)
}

overall_grade(student1)
overall_grade(student2)

overall_grade_2(student1)
overall_grade_2(student2)
```


```{r}
#library(bio3d)

#lbio3d()

# demo(package="bio3d")
# demo("nma")
```

